plugins:
  - jekyll-relative-links
  - jemoji
relative_links:
  enabled: true
include:
  - README.md
  - Diario.md
  - Bases.md
  - Entornos.md
  - Marcas.md
  - Programacion.md
  - Servidor.md