/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing.ejemplocompleto;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cic
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio1
     */
    private DefaultListModel<Inmueble> modeloLista;
    private BaseDatos bd = BaseDatos.getInstance();
    private DefaultTableModel modeloTabla;

    public Ventana() {
        initComponents();
        this.setLocationRelativeTo(null);
        Inicio.setVisible(true);
        Panel2.setVisible(false);
        Panel3.setVisible(false);
        mostrarImagen();
        cargarItems();
        modeloTabla = (DefaultTableModel) jTablePropietarios.getModel();
        this.modeloLista = new DefaultListModel<Inmueble>();

        jListInmuebles.setModel(modeloLista);

        jListInmuebles.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Inicio = new javax.swing.JPanel();
        lblIcono = new javax.swing.JLabel();
        btnWebsite = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabeltitulo = new javax.swing.JLabel();
        btnIniciarSesion = new javax.swing.JButton();
        Panel2 = new javax.swing.JPanel();
        jPanelDatosPropietario = new javax.swing.JPanel();
        jLabelNif = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        btnComprobar = new javax.swing.JButton();
        jPanelDatosInmueble = new javax.swing.JPanel();
        jLabelDireccion = new javax.swing.JLabel();
        jLabelLocalidad = new javax.swing.JLabel();
        jLabelAnio = new javax.swing.JLabel();
        jLabelSuperficie = new javax.swing.JLabel();
        jLabelPrecio = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        txtAnio = new javax.swing.JTextField();
        txtSuperficie = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        cmbLocalidad = new javax.swing.JComboBox<>();
        btnInsertar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        Panel3 = new javax.swing.JPanel();
        jScrollPanepropietarios = new javax.swing.JScrollPane();
        jTablePropietarios = new javax.swing.JTable();
        btnVolver2 = new javax.swing.JButton();
        btnBuscarInmuebles = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListInmuebles = new javax.swing.JList<>();
        InicioBanquero = new javax.swing.JPanel();
        InicioBanqueLbl = new javax.swing.JLabel();
        NumeroBanqueLbl = new javax.swing.JLabel();
        PasswordBanqueLbl = new javax.swing.JLabel();
        NumBanqueTxt = new javax.swing.JTextField();
        EntrarBanqBtn = new javax.swing.JButton();
        PasswordBanqueTxt = new javax.swing.JPasswordField();
        EntrarCliBtn = new javax.swing.JButton();
        OpcionesBanquero = new javax.swing.JPanel();
        MenOpLbl = new javax.swing.JLabel();
        OfrecerCreditoBtn = new javax.swing.JButton();
        ListarClientesBtn = new javax.swing.JButton();
        RegistrarClienteBtn = new javax.swing.JButton();
        RevisarSolicitudesBtn = new javax.swing.JButton();
        CerrarSesionBanqBtn = new javax.swing.JButton();
        InicioSesion = new javax.swing.JPanel();
        EnterBt = new javax.swing.JButton();
        InicioLbl = new javax.swing.JLabel();
        EnterBanqueroBt = new javax.swing.JToggleButton();
        UsuarioTxt = new javax.swing.JTextField();
        UsuarioLbl = new javax.swing.JLabel();
        PasswordLbl = new javax.swing.JLabel();
        PasswordUsuarioTxt = new javax.swing.JPasswordField();
        OpcionesUsuario = new javax.swing.JPanel();
        BienvenidoLbl = new javax.swing.JLabel();
        ConsultarCuentaBtn = new javax.swing.JButton();
        RealizarOperacionBtn = new javax.swing.JButton();
        ConsultarOfertasBtn = new javax.swing.JButton();
        AceptarPrestamoBtn = new javax.swing.JButton();
        SolicitarPrestamoBtn = new javax.swing.JButton();
        ConsultarPrestamosLbl = new javax.swing.JButton();
        CerrarSesionUsuBtn = new javax.swing.JButton();
        jMenuBarArchivo = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuItemGuardar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        btnWebsite.setText("Website");
        btnWebsite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWebsiteActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabeltitulo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabeltitulo.setForeground(new java.awt.Color(0, 153, 153));
        jLabeltitulo.setText("BANCO NUEVO PROYECTO");

        btnIniciarSesion.setText("Iniciar Sesión");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InicioLayout = new javax.swing.GroupLayout(Inicio);
        Inicio.setLayout(InicioLayout);
        InicioLayout.setHorizontalGroup(
            InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(InicioLayout.createSequentialGroup()
                        .addComponent(btnWebsite)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InicioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabeltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163))
        );

        InicioLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnIniciarSesion, btnSalir, btnWebsite});

        InicioLayout.setVerticalGroup(
            InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabeltitulo)
                .addGap(18, 18, 18)
                .addComponent(lblIcono, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnWebsite)
                    .addComponent(btnIniciarSesion)
                    .addComponent(btnSalir))
                .addGap(24, 24, 24))
        );

        InicioLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnIniciarSesion, btnSalir, btnWebsite});

        getContentPane().add(Inicio, "card2");

        jPanelDatosPropietario.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del propietario"));

        jLabelNif.setText("NIF:");

        jLabelNombre.setText("Nombre:");

        jLabelTelefono.setText("Telefono:");

        txtDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDNIActionPerformed(evt);
            }
        });

        btnComprobar.setText("Comprobar Propietario");
        btnComprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprobarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDatosPropietarioLayout = new javax.swing.GroupLayout(jPanelDatosPropietario);
        jPanelDatosPropietario.setLayout(jPanelDatosPropietarioLayout);
        jPanelDatosPropietarioLayout.setHorizontalGroup(
            jPanelDatosPropietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosPropietarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosPropietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelNif, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosPropietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosPropietarioLayout.createSequentialGroup()
                        .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnComprobar))
                    .addGroup(jPanelDatosPropietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNombre)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanelDatosPropietarioLayout.setVerticalGroup(
            jPanelDatosPropietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosPropietarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosPropietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNif)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComprobar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosPropietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosPropietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelefono)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanelDatosInmueble.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Inmueble"));

        jLabelDireccion.setText("Direccion:");

        jLabelLocalidad.setText("Localidad:");

        jLabelAnio.setText("Año de construccion:");

        jLabelSuperficie.setText("Superficie: ");

        jLabelPrecio.setText("Precio:");

        javax.swing.GroupLayout jPanelDatosInmuebleLayout = new javax.swing.GroupLayout(jPanelDatosInmueble);
        jPanelDatosInmueble.setLayout(jPanelDatosInmuebleLayout);
        jPanelDatosInmuebleLayout.setHorizontalGroup(
            jPanelDatosInmuebleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosInmuebleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosInmuebleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelLocalidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSuperficie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelAnio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosInmuebleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDireccion)
                    .addComponent(txtAnio)
                    .addComponent(txtSuperficie)
                    .addComponent(txtPrecio)
                    .addComponent(cmbLocalidad, 0, 228, Short.MAX_VALUE))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        jPanelDatosInmuebleLayout.setVerticalGroup(
            jPanelDatosInmuebleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosInmuebleLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanelDatosInmuebleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDireccion)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosInmuebleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLocalidad)
                    .addComponent(cmbLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosInmuebleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAnio)
                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosInmuebleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSuperficie)
                    .addComponent(txtSuperficie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosInmuebleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrecio)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        btnInsertar.setText("Insertar Inmueble");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel2Layout = new javax.swing.GroupLayout(Panel2);
        Panel2.setLayout(Panel2Layout);
        Panel2Layout.setHorizontalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelDatosPropietario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDatosInmueble, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnInsertar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 363, Short.MAX_VALUE)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Panel2Layout.setVerticalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanelDatosPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDatosInmueble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertar)
                    .addComponent(btnVolver))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(Panel2, "card3");

        jScrollPanepropietarios.setViewportView(jTablePropietarios);

        btnVolver2.setText("Volver");
        btnVolver2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolver2ActionPerformed(evt);
            }
        });

        btnBuscarInmuebles.setText("Buscar inmuebles");
        btnBuscarInmuebles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarInmueblesActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jListInmuebles);

        javax.swing.GroupLayout Panel3Layout = new javax.swing.GroupLayout(Panel3);
        Panel3.setLayout(Panel3Layout);
        Panel3Layout.setHorizontalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Panel3Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(btnBuscarInmuebles, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVolver2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel3Layout.createSequentialGroup()
                    .addContainerGap(56, Short.MAX_VALUE)
                    .addComponent(jScrollPanepropietarios, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(56, Short.MAX_VALUE)))
        );

        Panel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBuscarInmuebles, btnVolver2});

        Panel3Layout.setVerticalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel3Layout.createSequentialGroup()
                .addContainerGap(236, Short.MAX_VALUE)
                .addGroup(Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnBuscarInmuebles)
                    .addComponent(btnVolver2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel3Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPanepropietarios, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(234, Short.MAX_VALUE)))
        );

        Panel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBuscarInmuebles, btnVolver2});

        getContentPane().add(Panel3, "card4");

        InicioBanqueLbl.setText("INICIO SESIÓN");

        NumeroBanqueLbl.setText("Nº de empleado");

        PasswordBanqueLbl.setText("Contraseña");

        EntrarBanqBtn.setText("Entrar");
        EntrarBanqBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarBanqBtnActionPerformed(evt);
            }
        });

        EntrarCliBtn.setText("Entrar como cliente");
        EntrarCliBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarCliBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InicioBanqueroLayout = new javax.swing.GroupLayout(InicioBanquero);
        InicioBanquero.setLayout(InicioBanqueroLayout);
        InicioBanqueroLayout.setHorizontalGroup(
            InicioBanqueroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioBanqueroLayout.createSequentialGroup()
                .addGroup(InicioBanqueroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InicioBanqueroLayout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(InicioBanqueLbl))
                    .addGroup(InicioBanqueroLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(InicioBanqueroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NumeroBanqueLbl)
                            .addComponent(PasswordBanqueLbl))
                        .addGap(70, 70, 70)
                        .addGroup(InicioBanqueroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NumBanqueTxt)
                            .addComponent(PasswordBanqueTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(InicioBanqueroLayout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addGroup(InicioBanqueroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EntrarCliBtn)
                            .addGroup(InicioBanqueroLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(EntrarBanqBtn)))))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        InicioBanqueroLayout.setVerticalGroup(
            InicioBanqueroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioBanqueroLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(InicioBanqueLbl)
                .addGap(57, 57, 57)
                .addGroup(InicioBanqueroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InicioBanqueroLayout.createSequentialGroup()
                        .addComponent(NumBanqueTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(InicioBanqueroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PasswordBanqueTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PasswordBanqueLbl)))
                    .addComponent(NumeroBanqueLbl))
                .addGap(66, 66, 66)
                .addComponent(EntrarBanqBtn)
                .addGap(18, 18, 18)
                .addComponent(EntrarCliBtn)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        getContentPane().add(InicioBanquero, "card3");

        MenOpLbl.setText("MENÚ DE OPCIONES");

        OfrecerCreditoBtn.setText("Ofrecer Crédito");
        OfrecerCreditoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OfrecerCreditoBtnActionPerformed(evt);
            }
        });

        ListarClientesBtn.setText("Listar Clientes");

        RegistrarClienteBtn.setText("Registrar Cliente");

        RevisarSolicitudesBtn.setText("Revisar Solicitudes");

        CerrarSesionBanqBtn.setText("Cerrar Sesión");
        CerrarSesionBanqBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesionBanqBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OpcionesBanqueroLayout = new javax.swing.GroupLayout(OpcionesBanquero);
        OpcionesBanquero.setLayout(OpcionesBanqueroLayout);
        OpcionesBanqueroLayout.setHorizontalGroup(
            OpcionesBanqueroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OpcionesBanqueroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(OpcionesBanqueroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ListarClientesBtn)
                    .addComponent(OfrecerCreditoBtn))
                .addGap(78, 78, 78)
                .addGroup(OpcionesBanqueroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RevisarSolicitudesBtn)
                    .addComponent(RegistrarClienteBtn))
                .addGap(194, 194, 194))
            .addGroup(OpcionesBanqueroLayout.createSequentialGroup()
                .addGroup(OpcionesBanqueroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OpcionesBanqueroLayout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(MenOpLbl))
                    .addGroup(OpcionesBanqueroLayout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(CerrarSesionBanqBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        OpcionesBanqueroLayout.setVerticalGroup(
            OpcionesBanqueroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OpcionesBanqueroLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(MenOpLbl)
                .addGap(115, 115, 115)
                .addGroup(OpcionesBanqueroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OfrecerCreditoBtn)
                    .addComponent(RegistrarClienteBtn))
                .addGap(43, 43, 43)
                .addGroup(OpcionesBanqueroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ListarClientesBtn)
                    .addComponent(RevisarSolicitudesBtn))
                .addGap(53, 53, 53)
                .addComponent(CerrarSesionBanqBtn)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        getContentPane().add(OpcionesBanquero, "card4");

        EnterBt.setText("Entrar");
        EnterBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterBtActionPerformed(evt);
            }
        });

        InicioLbl.setText("INICIO SESIÓN");

        EnterBanqueroBt.setText("Entrar como personal del banco");
        EnterBanqueroBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterBanqueroBtActionPerformed(evt);
            }
        });

        UsuarioTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioTxtActionPerformed(evt);
            }
        });

        UsuarioLbl.setText("Usuario");

        PasswordLbl.setText("Contraseña");

        PasswordUsuarioTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordUsuarioTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InicioSesionLayout = new javax.swing.GroupLayout(InicioSesion);
        InicioSesion.setLayout(InicioSesionLayout);
        InicioSesionLayout.setHorizontalGroup(
            InicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioSesionLayout.createSequentialGroup()
                .addGroup(InicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InicioSesionLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(InicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PasswordLbl)
                            .addComponent(UsuarioLbl))
                        .addGap(36, 36, 36)
                        .addGroup(InicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InicioLbl)
                            .addGroup(InicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(UsuarioTxt)
                                .addComponent(PasswordUsuarioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(EnterBt)))
                    .addGroup(InicioSesionLayout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(EnterBanqueroBt)))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        InicioSesionLayout.setVerticalGroup(
            InicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioSesionLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(InicioLbl)
                .addGap(43, 43, 43)
                .addGroup(InicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsuarioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsuarioLbl))
                .addGap(30, 30, 30)
                .addGroup(InicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordLbl)
                    .addComponent(PasswordUsuarioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(EnterBt)
                .addGap(18, 18, 18)
                .addComponent(EnterBanqueroBt)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        getContentPane().add(InicioSesion, "card3");

        BienvenidoLbl.setText("Bienvenido!");

        ConsultarCuentaBtn.setText("Consultar mi cuenta");

        RealizarOperacionBtn.setText("Realizar Operación");

        ConsultarOfertasBtn.setText("Consultar préstamos preconcedidos");
        ConsultarOfertasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarOfertasBtnActionPerformed(evt);
            }
        });

        AceptarPrestamoBtn.setText("Aceptar préstamo preconcedido");

        SolicitarPrestamoBtn.setText("Solicitar préstamo");
        SolicitarPrestamoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SolicitarPrestamoBtnActionPerformed(evt);
            }
        });

        ConsultarPrestamosLbl.setText("Consultar el estado de mis préstamos");

        CerrarSesionUsuBtn.setText("Cerrar Sesión");
        CerrarSesionUsuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesionUsuBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OpcionesUsuarioLayout = new javax.swing.GroupLayout(OpcionesUsuario);
        OpcionesUsuario.setLayout(OpcionesUsuarioLayout);
        OpcionesUsuarioLayout.setHorizontalGroup(
            OpcionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OpcionesUsuarioLayout.createSequentialGroup()
                .addGroup(OpcionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OpcionesUsuarioLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(OpcionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ConsultarCuentaBtn)
                            .addComponent(SolicitarPrestamoBtn)
                            .addComponent(RealizarOperacionBtn))
                        .addGap(111, 111, 111)
                        .addGroup(OpcionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AceptarPrestamoBtn)
                            .addComponent(ConsultarOfertasBtn)
                            .addComponent(ConsultarPrestamosLbl)))
                    .addGroup(OpcionesUsuarioLayout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(CerrarSesionUsuBtn))
                    .addGroup(OpcionesUsuarioLayout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(BienvenidoLbl)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        OpcionesUsuarioLayout.setVerticalGroup(
            OpcionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OpcionesUsuarioLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(BienvenidoLbl)
                .addGap(90, 90, 90)
                .addGroup(OpcionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConsultarCuentaBtn)
                    .addComponent(ConsultarOfertasBtn))
                .addGap(18, 18, 18)
                .addGroup(OpcionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RealizarOperacionBtn)
                    .addComponent(AceptarPrestamoBtn))
                .addGap(26, 26, 26)
                .addGroup(OpcionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SolicitarPrestamoBtn)
                    .addComponent(ConsultarPrestamosLbl))
                .addGap(65, 65, 65)
                .addComponent(CerrarSesionUsuBtn)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        getContentPane().add(OpcionesUsuario, "card5");

        jMenuArchivo.setText("Archivo");

        jMenuItemGuardar.setText("Guardar");
        jMenuItemGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGuardarActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemGuardar);
        jMenuArchivo.add(jSeparator1);

        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemSalir);

        jMenuBarArchivo.add(jMenuArchivo);

        setJMenuBar(jMenuBarArchivo);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarItems(){
        cmbLocalidad.addItem("Torrelavega");
        cmbLocalidad.addItem("Santander");
        cmbLocalidad.addItem("Renedo");
        cmbLocalidad.addItem("Cabezón de la Sal");
        cmbLocalidad.addItem("Suances");
    }
    private void mostrarImagen() {
        ImageIcon img = new ImageIcon(getClass().getClassLoader().getResource("Imagen/casas.jpg"));
        Icon icon = new ImageIcon(img.getImage().
                getScaledInstance(lblIcono.getWidth(),
                        lblIcono.getHeight(), img.getIconWidth()));
        lblIcono.setIcon(icon);
    }
    private void escribirFichero(){
        ObjectOutputStream oos = null;
        File fichero = new File("propietarios.dat");
        ArrayList<Propietario> lista = new ArrayList<>();
        lista = bd.consultarPropietarios();
        try {
            if (fichero.exists()) {
                oos = new MiObjectOutputStream(new FileOutputStream(fichero, true));

            } else {
                oos = new ObjectOutputStream(new FileOutputStream(fichero));
            }
            for (Propietario p : lista) {

                oos.writeObject(p);
            }
        } catch (IOException ex) {
            System.out.println("Error de lectura o escritura del fichero.");
        } finally {
            try {
                if (oos!=null)
                oos.close();
            } catch (IOException ex) {
                System.out.println("Error al cerrar el fichero");
            }
        }
    }
    private void btnWebsiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWebsiteActionPerformed
//        // TODO add your handling code here:
//        Panel1.setVisible(false);
//        Panel2.setVisible(true);
//        Panel3.setVisible(false);
//        txtNombre.setEnabled(false);
//        txtTelefono.setEnabled(false);
    }//GEN-LAST:event_btnWebsiteActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        // TODO add your handling code here:
        Inicio.setVisible(false);
        Panel2.setVisible(false);
        Panel3.setVisible(false);
        InicioSesion.setVisible(true);
        InicioBanquero.setVisible(false);
        OpcionesBanquero.setVisible(false);
        OpcionesUsuario.setVisible(false);
//        Object[][] obj = bd.consultaPropietarios();
//        String[] titulares = {"DNI", "nombre", "telefono"};
//        modeloTabla = new DefaultTableModel(null, titulares);
//        jTablePropietarios.setModel(modeloTabla);
//        for (int i = 0; i < obj.length; i++) {
//            modeloTabla.addRow(obj[i]);
//        }

    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void txtDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNIActionPerformed

    private void btnComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprobarActionPerformed
        // TODO add your handling code here:
        if (!txtDNI.getText().equals("")) {
            Propietario p = bd.seleccionPropietario(txtDNI.getText());
            if (p != null) {
                txtNombre.setText(p.getNombre());
                txtTelefono.setText(p.getTelefono());

            } else {
                txtNombre.setEnabled(true);
                txtTelefono.setEnabled(true);
            }
        }
    }//GEN-LAST:event_btnComprobarActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        // TODO add your handling code here:
        Propietario p = new Propietario(txtDNI.getText(), txtNombre.getText(), txtTelefono.getText());
        Inmueble i = new Inmueble(txtDireccion.getText(), (String) cmbLocalidad.getSelectedItem(), txtAnio.getText(), Integer.parseInt(txtSuperficie.getText()), txtDNI.getText(), Integer.parseInt(txtPrecio.getText()));
        bd.Insertar(p, i);
        txtDNI.setText("");
        txtNombre.setText("");
        txtTelefono.setText("");
        txtDireccion.setText("");
        cmbLocalidad.setSelectedItem(null);
        txtAnio.setText("");
        txtSuperficie.setText("");
        txtPrecio.setText("");
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        Inicio.setVisible(true);
        Panel2.setVisible(false);
        Panel3.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnVolver2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver2ActionPerformed
        // TODO add your handling code here:
        Inicio.setVisible(true);
        Panel2.setVisible(false);
        Panel3.setVisible(false);
    }//GEN-LAST:event_btnVolver2ActionPerformed

    private void btnBuscarInmueblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarInmueblesActionPerformed
        // TODO add your handling code here:
        modeloLista.clear();
        int fila = jTablePropietarios.getSelectedRow();
        if (fila != -1) {
            String id = (String) jTablePropietarios.getValueAt(fila, 0);

            ArrayList<Inmueble> obj = bd.consultaInmueblesDelPropietario(id);
            for (Inmueble inm : obj) {
                modeloLista.addElement(inm);
            }
        } else {
        JOptionPane.showMessageDialog(null,
                        "hay que seleccionar un propietario primero",
                        "Advertencia", JOptionPane.WARNING_MESSAGE,null);
        }

    }//GEN-LAST:event_btnBuscarInmueblesActionPerformed

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jMenuItemGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGuardarActionPerformed
        escribirFichero();
    }//GEN-LAST:event_jMenuItemGuardarActionPerformed

    private void EntrarBanqBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarBanqBtnActionPerformed
        Inicio.setVisible(false);
        InicioBanquero.setVisible(false);
        OpcionesBanquero.setVisible(true);
        OpcionesUsuario.setVisible(false);
        InicioSesion.setVisible(false);
        Panel2.setVisible(false);
        Panel3.setVisible(false);
    }//GEN-LAST:event_EntrarBanqBtnActionPerformed

    private void EntrarCliBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarCliBtnActionPerformed
        Inicio.setVisible(false);
        InicioSesion.setVisible(true);
        InicioBanquero.setVisible(false);
        OpcionesBanquero.setVisible(false);
        OpcionesUsuario.setVisible(false);
        Panel2.setVisible(false);
        Panel3.setVisible(false);
    }//GEN-LAST:event_EntrarCliBtnActionPerformed

    private void OfrecerCreditoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OfrecerCreditoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OfrecerCreditoBtnActionPerformed

    private void CerrarSesionBanqBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesionBanqBtnActionPerformed
        Inicio.setVisible(true);
        InicioBanquero.setVisible(false);
        OpcionesBanquero.setVisible(false);
        OpcionesUsuario.setVisible(false);
        InicioSesion.setVisible(false);
        Panel2.setVisible(false);
        Panel3.setVisible(false);
    }//GEN-LAST:event_CerrarSesionBanqBtnActionPerformed

    private void EnterBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterBtActionPerformed
        InicioSesion.setVisible(false);
        InicioBanquero.setVisible(false);
        OpcionesBanquero.setVisible(false);
        OpcionesUsuario.setVisible(true);
        Inicio.setVisible(false);
        Panel2.setVisible(false);
        Panel3.setVisible(false);
        
    }//GEN-LAST:event_EnterBtActionPerformed

    private void EnterBanqueroBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterBanqueroBtActionPerformed
        InicioSesion.setVisible(false);
        InicioBanquero.setVisible(true);
        OpcionesBanquero.setVisible(false);
        OpcionesUsuario.setVisible(false);
        Panel2.setVisible(false);
        Panel3.setVisible(false);
        Inicio.setVisible(false);
    }//GEN-LAST:event_EnterBanqueroBtActionPerformed

    private void UsuarioTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioTxtActionPerformed

    private void PasswordUsuarioTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordUsuarioTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordUsuarioTxtActionPerformed

    private void ConsultarOfertasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarOfertasBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultarOfertasBtnActionPerformed

    private void SolicitarPrestamoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SolicitarPrestamoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SolicitarPrestamoBtnActionPerformed

    private void CerrarSesionUsuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesionUsuBtnActionPerformed
        InicioSesion.setVisible(false);
        InicioBanquero.setVisible(false);
        OpcionesBanquero.setVisible(false);
        OpcionesUsuario.setVisible(false);
        Inicio.setVisible(true);
        Panel2.setVisible(false);
        Panel3.setVisible(false);
    }//GEN-LAST:event_CerrarSesionUsuBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarPrestamoBtn;
    private javax.swing.JLabel BienvenidoLbl;
    private javax.swing.JButton CerrarSesionBanqBtn;
    private javax.swing.JButton CerrarSesionUsuBtn;
    private javax.swing.JButton ConsultarCuentaBtn;
    private javax.swing.JButton ConsultarOfertasBtn;
    private javax.swing.JButton ConsultarPrestamosLbl;
    private javax.swing.JToggleButton EnterBanqueroBt;
    private javax.swing.JButton EnterBt;
    private javax.swing.JButton EntrarBanqBtn;
    private javax.swing.JButton EntrarCliBtn;
    private javax.swing.JPanel Inicio;
    private javax.swing.JLabel InicioBanqueLbl;
    private javax.swing.JPanel InicioBanquero;
    private javax.swing.JLabel InicioLbl;
    private javax.swing.JPanel InicioSesion;
    private javax.swing.JButton ListarClientesBtn;
    private javax.swing.JLabel MenOpLbl;
    private javax.swing.JTextField NumBanqueTxt;
    private javax.swing.JLabel NumeroBanqueLbl;
    private javax.swing.JButton OfrecerCreditoBtn;
    private javax.swing.JPanel OpcionesBanquero;
    private javax.swing.JPanel OpcionesUsuario;
    private javax.swing.JPanel Panel2;
    private javax.swing.JPanel Panel3;
    private javax.swing.JLabel PasswordBanqueLbl;
    private javax.swing.JPasswordField PasswordBanqueTxt;
    private javax.swing.JLabel PasswordLbl;
    private javax.swing.JPasswordField PasswordUsuarioTxt;
    private javax.swing.JButton RealizarOperacionBtn;
    private javax.swing.JButton RegistrarClienteBtn;
    private javax.swing.JButton RevisarSolicitudesBtn;
    private javax.swing.JButton SolicitarPrestamoBtn;
    private javax.swing.JLabel UsuarioLbl;
    private javax.swing.JTextField UsuarioTxt;
    private javax.swing.JButton btnBuscarInmuebles;
    private javax.swing.JButton btnComprobar;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton btnVolver2;
    private javax.swing.JButton btnWebsite;
    private javax.swing.JComboBox<String> cmbLocalidad;
    private javax.swing.JLabel jLabelAnio;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelLocalidad;
    private javax.swing.JLabel jLabelNif;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelSuperficie;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabeltitulo;
    private javax.swing.JList<Inmueble> jListInmuebles;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuBar jMenuBarArchivo;
    private javax.swing.JMenuItem jMenuItemGuardar;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JPanel jPanelDatosInmueble;
    private javax.swing.JPanel jPanelDatosPropietario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPanepropietarios;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable jTablePropietarios;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtSuperficie;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
